name: Publish

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.5.0
          run_install: true
          
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: pnpm

      - name: Build Viewer Package
        run: pnpm build:viewer

      - name: Publish to npm
        run: pnpm publish viewer --access public --no-git-checks

