name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        run: npm install -g pnpm@9

      - name: Install dependencies
        run: pnpm install

      - name: Build app
        run: pnpm run build

      - name: Generate the package
        run: tar -czpf dist.tar.gz sites/app/dist LICENSE

      - name: Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: dist.tar.gz
        
      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: pnpm exec semantic-release
